@baseUrl = http://localhost:3000


###
GET {{baseUrl}} HTTP/1.1



###
curl -X POST http://localhost:3000/cnab/generate \
-H "Content-Type: application/json" \
-d '{
  "empresa": {
    "nome": "Empresa Teste",
    "banco": 341,
    "formato": 240,
    "versao": 86,
    "inscricao_tipo": 2,
    "inscricao_numero": "12345678000195",
    "convenio": "123456",
    "agencia": "1234",
    "agencia_dv": "1",
    "conta": "12345678",
    "conta_dv": "1",
    "nome_banco": "Banco Itaú"
  },
  "pagamentos": [
    {
      "tipo": 20,
      "valor": 1000.50,
      "favorecido": {
        "nome": "Fornecedor A",
        "cpf_cnpj": "12345678901",
        "banco": 341,
        "agencia": "5678",
        "agencia_dv": "0",
        "conta": "87654321",
        "conta_dv": "2"
      },
      "data_pagamento": "2025-04-22",
      "descricao": "Pagamento de serviços"
    }
  ]
}'